name: San Francisco LGBT Pride Parade and Celebration Committee, Inc.
title: San Francisco Pride
url: https://members.sfpride.org
description: a temporary resource site for SF Pride members

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - github-pages

sass:
  load_paths:
    - _sass
  style: compressed